"""initial schema

Revision ID: b129b8bc80c6
Revises: 
Create Date: 2026-08-03 10:53:13.578387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b129b8bc80c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threshold_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threshold_rules')),
    sa.UniqueConstraint('key', name=op.f('uq_threshold_rules_key'))
    )
    op.create_index(op.f('ix_threshold_rules_metric'), 'threshold_rules', ['metric'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('systolic', sa.Float(), nullable=True),
    sa.Column('diastolic', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_health_records_patient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_records'))
    )
    op.create_index(op.f('ix_health_records_patient_id'), 'health_records', ['patient_id'], unique=False)
    op.create_index('ix_health_records_patient_type_time', 'health_records', ['patient_id', 'record_type', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_health_records_record_type'), 'health_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_health_records_recorded_at'), 'health_records', ['recorded_at'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('therapist_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=20), nullable=False),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_matches_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_matches_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_matches_therapist_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_patient_id'), 'matches', ['patient_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_therapist_id'), 'matches', ['therapist_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_messages_recipient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_pair_time', 'messages', ['sender_id', 'recipient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('discharge_summary', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patient_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_profiles_user_id'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('rehab_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('therapist_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_rehab_plans_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_rehab_plans_therapist_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rehab_plans'))
    )
    op.create_index(op.f('ix_rehab_plans_patient_id'), 'rehab_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_rehab_plans_status'), 'rehab_plans', ['status'], unique=False)
    op.create_index(op.f('ix_rehab_plans_therapist_id'), 'rehab_plans', ['therapist_id'], unique=False)
    op.create_table('therapist_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_docs', sa.Text(), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_therapist_profiles_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_therapist_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapist_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_therapist_profiles_user_id'))
    )
    op.create_index(op.f('ix_therapist_profiles_status'), 'therapist_profiles', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('health_record_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by', sa.Uuid(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handler_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], name=op.f('fk_alerts_handled_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.id'], name=op.f('fk_alerts_health_record_id_health_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_alerts_patient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_patient_id'), 'alerts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['rehab_plans.id'], name=op.f('fk_plan_tasks_plan_id_rehab_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_tasks'))
    )
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_table('plan_checkins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_plan_checkins_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], name=op.f('fk_plan_checkins_task_id_plan_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_checkins')),
    sa.UniqueConstraint('task_id', 'patient_id', 'checkin_date', name='uq_checkin_task_patient_date')
    )
    op.create_index(op.f('ix_plan_checkins_patient_id'), 'plan_checkins', ['patient_id'], unique=False)
    op.create_index(op.f('ix_plan_checkins_task_id'), 'plan_checkins', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_checkins_task_id'), table_name='plan_checkins')
    op.drop_index(op.f('ix_plan_checkins_patient_id'), table_name='plan_checkins')
    op.drop_table('plan_checkins')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patient_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_therapist_profiles_status'), table_name='therapist_profiles')
    op.drop_table('therapist_profiles')
    op.drop_index(op.f('ix_rehab_plans_therapist_id'), table_name='rehab_plans')
    op.drop_index(op.f('ix_rehab_plans_status'), table_name='rehab_plans')
    op.drop_index(op.f('ix_rehab_plans_patient_id'), table_name='rehab_plans')
    op.drop_table('rehab_plans')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index('ix_messages_pair_time', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_matches_therapist_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_patient_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_health_records_recorded_at'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_record_type'), table_name='health_records')
    op.drop_index('ix_health_records_patient_type_time', table_name='health_records')
    op.drop_index(op.f('ix_health_records_patient_id'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threshold_rules_metric'), table_name='threshold_rules')
    op.drop_table('threshold_rules')
    # ### end Alembic commands ###
